apiVersion: v2
name: dependency-track
version: 0.9.1
type: application
appVersion: 4.11.3
description: |-
  Dependency-Track is an intelligent Component Analysis platform
  that allows organizations to identify and reduce risk in the software supply chain.
home: https://github.com/Matt861/dependency-track
sources:
  - https://github.com/Matt861/dtrack-helm-charts/tree/main/charts/dependency-track
icon: https://avatars.githubusercontent.com/u/40258585
maintainers:
  - name: nscuro
    email: nscuro@protonmail.com
    url: https://github.com/nscuro
dependencies:
- name: postgresql
  version: ~10.10
  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
  condition: postgresql.enabled
